version: '3.3'

services:
    bot:
        build: ./bot
        container_name: bug_bot
        depends_on: 
            - dashboard
        restart: always

        network_mode: host

    dashboard: 
        build: ./dashboard
        container_name: bug_dashboard
        restart: always
        
        ports:
            - 3456:3456
        network_mode: host