tool: https://bugs.example.com

postgres:
  host: 127.0.0.1
  port: 5432

  user: someuser
  password: youshallnotpass
  database: bugbot

reward_role: 123456789098765432 # Contributor
stances_needed: 3
max_notes: 3

channels:
  approval: 123456789098765432 # approval-queue
  denied: 123456789098765432 # denied-bugs

boards:
  123456789098765432: # some-bugs
    repo: owner/repo
    token: no.token-4.u
    color: ff0000

roles:
  everyone: # @everyone
    - CAN_REPORT
    - CAN_EDIT

  123456789098765432: # Contributor
    - CAN_APPROVE
    - CAN_DENY
    - CAN_REVOKE
    - CAN_ATTACH

  123456789098765432: # Admins
    - CAN_FORCE_APPROVE
    - CAN_FORCE_DENY
    - CAN_NOTE  
    - CAN_LOCK
    - CAN_UNLOCK
  123456789098765432: # Mods
    - CAN_FORCE_APPROVE
    - CAN_FORCE_DENY
  123456789098765432: # Trial Mods
    - CAN_FORCE_DENY