token: no-token.4.u
tool: https://bugs.example.com

figlet:
  start: BugBot
  stop: Goodbye

  width: 80
  font: standard

logging:
  log_level: verbose
  project_name: bugbot

prefix:
  default: "!"
  aliases:
    - bugbot.
  mention: true

version:
  major: 1
  minor: 0
  patch: 0
  release: stable

postgres:
  host: 127.0.0.1
  port: 5432

  user: someuser
  password: youshallnotpass
  database: bugbot

reward_role: 123456789098765432 # Contributor
stances_needed: 3
max_notes: 3

channels:
  approval: 123456789098765432 # approval-queue
  denied: 123456789098765432 # denied-bugs

boards:
  123456789098765432: # some-bugs
    repo: owner/repo
    token: no.token-4.u

roles:
  everyone: # @everyone
    - CAN_REPORT
    - CAN_EDIT

  123456789098765432: # Contributor
    - CAN_APPROVE
    - CAN_DENY
    - CAN_REVOKE
    - CAN_ATTACH

  123456789098765432: # Admins
    - CAN_FORCE_APPROVE
    - CAN_FORCE_DENY
    - CAN_NOTE  
  123456789098765432: # Mods
    - CAN_FORCE_APPROVE
    - CAN_FORCE_DENY
  123456789098765432: # Trial Mods
    - CAN_FORCE_DENY

formats:
  DM_APPROVE: |-
    :tada: The bug you reported earlier (#{id}) has been approved! Thanks for your help!

  DM_DENY: |-
    :frowning: The bug you reported earlier (#{id}) has been denied because:
    {repros}

  REPORT: |-
    ───────────────────
    {channel.mention} **{reporter}** reported:
    
    **Short description:** {short}
    **Steps to reproduce:**
    {steps}
    **Expected result:** {expected}
    **Actual result:** {actual}
    **Software version:** {software}

    The report above needs to be approved.
    Report ID: **{id}**
    {repros_and_extras}

  REPRO: "{emoji} **{author}**: `{content}`"
  NOTE: "{emoji} **{author}**: `{content}`"
  ATTACHMENT: "{emoji} **{author}**: {content}"

  APPROVED_BUG: |-
    ───────────────────────
    Reported by: **{reporter}**

    **Short description:** {short}
    **Steps to reproduce:**
    {steps}
    **Expected result:** {expected}
    **Actual result:** {actual}
    **Software version:** {software}
    <{issue_url}> - **#{id}**

    **Reproducibility:**
    {repros_and_extras}

  DENIED_BUG: |-
    ───────────────────
    {channel.mention}: **#{id}**
    **{reporter}** reported:
    
    **Short description:** {short}
    **Steps to reproduce:**
    {steps}
    **Expected result:** {expected}
    **Actual result:** {actual}
    **Software version:** {software}

    {repros_and_extras}

  GH_ISSUE:
    TITLE: "#{id} - {short}"
    BODY: |-
      **Reported by:** {reporter}

      ### Short Description
      {short}

      ### Steps to Reproduce
      {steps}

      ### Expected Result
      {expected}

      ### Actual Result
      {actual}

      **Software version:** {software}

      ### Reproducibility
      {reproducibility}

      ### Attachments
      {attachments}

      ### Development Notes
      {notes}